### ISSUE TITLE
Cannot read property 'incremental' of undefined

### ISSUE THREAD

**Issue by niks3089** [nimbella/commander-cli#12] opened 2020-10-09 14:00 UTC
```
 nc> csm_install ./nimbella
  ✔ Packaging nimbella...
  ✔ Uploading nimbella...
Error: Cannot read property 'incremental' of undefined
```

**Comment by satyarohith** [comment] 2020-10-12 02:07
I couldn't reproduce the issue. Maybe the new changes might fix it. Let me know if this persists after changes from #14.

**Comment by satyarohith** [comment] 2020-10-12 12:39
Closing this for now. Feel free to re-open if the error pops up again.

**Closed as completed by satyarohith** 2020-10-12 12:39 UTC
Labels: bug
